repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-added-large-files

  - repo: https://github.com/PyCQA/flake8
    rev:  7.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-print]

  - repo: local
    hooks:
        - id: protect-main-branch
          name: Protect main branch
          entry: ./hooks/protect-main-branch.sh
          language: script
          stages: [commit]

default_stages: [commit]