name: Feature Branch Quality Check

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install pre-commit
        run: |
          pip install pre-commit
      - name: Run pre-commit
        run: |
          pre-commit run --all-files